################################################################################
#
# fakeroot
#
################################################################################

FAKEROOT_VERSION = 1.20.2
FAKEROOT_SOURCE = fakeroot_$(FAKEROOT_VERSION).orig.tar.bz2
FAKEROOT_SITE = http://snapshot.debian.org/archive/debian/20141005T221953Z/pool/main/f/fakeroot

HOST_FAKEROOT_DEPENDENCIES = host-acl
# Force capabilities detection off
# For now these are process capabilities (faked) rather than file
# so they're of no real use
HOST_FAKEROOT_CONF_ENV = \
	ac_cv_header_sys_capability_h=no \
	ac_cv_func_capset=no
# 0003-Select-TCP-when-lack-of-SYSV-IPC.patch touches configure.ac
HOST_FAKEROOT_AUTORECONF = YES
FAKEROOT_LICENSE = GPL-3.0+
FAKEROOT_LICENSE_FILES = COPYING

define HOST_FAKEROOT_BUILD_AUX
	mkdir -p $(@D)/build-aux
endef
HOST_FAKEROOT_POST_PATCH_HOOKS += HOST_FAKEROOT_BUILD_AUX

# ─── glibc 2.33+ 호환 wrapper (project-local fix) ───
# fakeroot 1.20.2 의 libfakeroot.so 는 stat64 ABI 변경 후 mknod 등 syscall
# intercept 실패 (Ubuntu 22.04 / glibc 2.35 에서 buildroot-fs/cpio rootfs.cpio
# 생성 시 "Operation not permitted"). 시스템 fakeroot 1.25+ 가 있으면
# install 후 wrapper 로 교체. 0005-glibc-2.33-STAT_VER-compat.patch 와 함께
# 적용해야 완전한 호환성 보장.
# 시스템 fakeroot 미존재 시 빌드한 1.20.2 그대로 사용 (mknod 단계에서 실패할 수
# 있으므로 WARN 출력). 정석은 `apt install fakeroot`.
define HOST_FAKEROOT_WRAP_SYSTEM
	@if command -v /usr/bin/fakeroot >/dev/null 2>&1; then \
		echo ">>> host-fakeroot: glibc 2.33+ 호환 위해 시스템 /usr/bin/fakeroot wrapper 적용"; \
		mv $(HOST_DIR)/bin/fakeroot $(HOST_DIR)/bin/fakeroot.builtin; \
		printf '#!/bin/bash\n# Auto-generated by fakeroot.mk POST_INSTALL hook.\n# Wrap system fakeroot for glibc 2.33+ compat (buildroot 1.20.2 broken).\nexec /usr/bin/fakeroot "$$@"\n' > $(HOST_DIR)/bin/fakeroot; \
		chmod +x $(HOST_DIR)/bin/fakeroot; \
	else \
		echo "!!! host-fakeroot: /usr/bin/fakeroot 미설치 — buildroot 1.20.2 그대로 사용 (mknod intercept 실패 가능). 'sudo apt install fakeroot' 권장."; \
	fi
endef
HOST_FAKEROOT_POST_INSTALL_HOOKS += HOST_FAKEROOT_WRAP_SYSTEM

$(eval $(host-autotools-package))
